name: Update Space Shooter Game

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Space Shooter
        uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: nakuldevmv
          output-path: game.gif
          strategy: random
